services:
  postgres_simplebank:
    image: postgres:14-alpine

    container_name: pg-simplebank
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simplebank
    ports:
      - "5438:5432"
    volumes:
      - ./db-data/pg-simplebank/:/var/lib/postgresql/data/
    networks:
      - bank-network
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://postgres:secret@postgres_simplebank:5432/simplebank?sslmode=disable
    depends_on:
      - postgres_simplebank
    entrypoint: [ "/app/wait-for.sh", "postgres_simplebank:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge