name: Deploy to production 

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    name: Build image
    runs-on: ubuntu-latest
    
    env:
      DB_SOURCE: ${{ secrets.DB_SOURCE }}
      TOKEN_SYMMETRIC_KEY: ${{ secrets.TOKEN_SYMMETRIC_KEY }}

    steps:
      # https://github.com/marketplace/actions/amazon-ecr-login-action-for-github-actions 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # outdated - do not recomend to use 
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS__SECRET_ACCESS_KEY }}          
          # use either role-to-assume with OIDC    or aws acces keys  
          # https://github.com/aws-actions/configure-aws-credentials#assuming-a-role  
          role-to-assume: arn:aws:iam::327784329477:role/simplebank-github-ci
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: simplebank
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
      
